#!/usr/bin/env python3
"""Fetch latest Allbeauty gold quote and write data/gold-quote.json + js/gold-quote-data.js.

Hourly CI POSTs the JSON to /api/gold-refresh (cache-only). It must not commit
these files — they stay in the repo as last-resort bootstrap only.
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.bot_gold import fetch_bot_gold_quote  # noqa: E402

OUT = ROOT / "data" / "gold-quote.json"
JS_OUT = ROOT / "public" / "js" / "gold-quote-data.js"


async def main() -> None:
    payload = await fetch_bot_gold_quote()
    quote = payload["quote"]
    metals = payload.get("metals") or {}
    body = {
        "quote": quote,
        "alloyRates": payload["alloyRates"],
        "metals": metals,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(body, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    js_body = (
        "/* Auto-generated by scripts/fetch_gold_quote.py — Allbeauty gold + Kitco silver fallback. */\n"
        f"window.__GOLD_QUOTE_BOOTSTRAP__ = {json.dumps(body, ensure_ascii=False, indent=2)};\n"
    )
    JS_OUT.parent.mkdir(parents=True, exist_ok=True)
    JS_OUT.write_text(js_body, encoding="utf-8")

    print("Wrote", OUT)
    print("Wrote", JS_OUT)
    print("XAU/g:", quote["sell"], "stamp:", quote.get("bot_posted_at"))
    if metals.get("XAG") is not None:
        print("XAG/g:", metals["XAG"], "s925:", payload["alloyRates"].get("s925"))


if __name__ == "__main__":
    asyncio.run(main())
