#!/usr/bin/env python3
"""Fetch latest BOT gold quote and write data/gold-quote.json + js/gold-quote-data.js."""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.bot_gold import fetch_bot_gold_quote  # noqa: E402

OUT = ROOT / "data" / "gold-quote.json"
JS_OUT = ROOT / "js" / "gold-quote-data.js"


async def main() -> None:
    payload = await fetch_bot_gold_quote()
    quote = payload["quote"]
    body = {"quote": quote, "alloyRates": payload["alloyRates"]}

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(body, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    js_body = (
        "/* Auto-generated by scripts/fetch_gold_quote.py — embedded BOT quote fallback. */\n"
        f"window.__GOLD_QUOTE_BOOTSTRAP__ = {json.dumps(body, ensure_ascii=False, indent=2)};\n"
    )
    JS_OUT.write_text(js_body, encoding="utf-8")

    print("Wrote", OUT)
    print("Wrote", JS_OUT)
    print("XAU/g:", quote["sell"], "stamp:", quote.get("bot_posted_at"))


if __name__ == "__main__":
    asyncio.run(main())
